<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_manda userPersonal DetailsContact DetailsEmergency ContactsDependentsImmigrationJobSalaryReport-toQualificationsMembershipsAssigned Immigration Records Add (1) Record FoundDocumentNumberIssued ByIssued DateExpiry Dat</name>
   <tag></tag>
   <elementGuidId>b0d11268-2cf4-403c-af36-87b689546492</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.orangehrm-background-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cca57c11-d113-4fff-a6d4-c0f495381aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>orangehrm-background-container</value>
      <webElementGuid>38055d8b-2fbf-4313-91e4-6d34aee3eb77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>manda userPersonal DetailsContact DetailsEmergency ContactsDependentsImmigrationJobSalaryReport-toQualificationsMembershipsAssigned Immigration Records Add (1) Record FoundDocumentNumberIssued ByIssued DateExpiry DateActionsPassport34Romania2019-10-102029-09-10Attachments Add (1) Record FoundFile NameDescriptionSizeTypeDate AddedAdded ByActionsImmigration.txtsum is simply dummy text of the printing24.00 Btext/plain2023-17-07Admin</value>
      <webElementGuid>a74b6376-979f-4b4e-bb74-0b5c81b5116d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout orangehrm-upgrade-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;orangehrm-background-container&quot;]</value>
      <webElementGuid>60cc3a6d-0b75-4bb6-a23e-3a8841fccd7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div</value>
      <webElementGuid>7d71158a-5f5c-44bb-a7da-266d84132e2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>754e47c8-e868-4a3f-9983-e2580358a11e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'manda userPersonal DetailsContact DetailsEmergency ContactsDependentsImmigrationJobSalaryReport-toQualificationsMembershipsAssigned Immigration Records Add (1) Record FoundDocumentNumberIssued ByIssued DateExpiry DateActionsPassport34Romania2019-10-102029-09-10Attachments Add (1) Record FoundFile NameDescriptionSizeTypeDate AddedAdded ByActionsImmigration.txtsum is simply dummy text of the printing24.00 Btext/plain2023-17-07Admin' or . = 'manda userPersonal DetailsContact DetailsEmergency ContactsDependentsImmigrationJobSalaryReport-toQualificationsMembershipsAssigned Immigration Records Add (1) Record FoundDocumentNumberIssued ByIssued DateExpiry DateActionsPassport34Romania2019-10-102029-09-10Attachments Add (1) Record FoundFile NameDescriptionSizeTypeDate AddedAdded ByActionsImmigration.txtsum is simply dummy text of the printing24.00 Btext/plain2023-17-07Admin')]</value>
      <webElementGuid>87836a9a-f928-4163-8deb-306e0e2e39a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
