<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_manda userPersonal DetailsContact DetailsEmergency ContactsDependentsImmigrationJobSalaryReport-toQualificationsMembershipsAssigned Memberships Add No Records FoundMembershipSubscription Paid BySubscription AmountCur</name>
   <tag></tag>
   <elementGuidId>c1f5b23d-8d2f-4380-b3d2-d53bf7c9cb8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.orangehrm-background-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>98959d20-77f0-4e5f-aa37-fcbbf0197957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>orangehrm-background-container</value>
      <webElementGuid>ba42a949-1328-4415-8c91-52e6592f51c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>manda userPersonal DetailsContact DetailsEmergency ContactsDependentsImmigrationJobSalaryReport-toQualificationsMembershipsAssigned Memberships Add No Records FoundMembershipSubscription Paid BySubscription AmountCurrencySubscription Commence DateSubscription Renewal DateActionsAttachments Add (1) Record FoundFile NameDescriptionSizeTypeDate AddedAdded ByActionsabc.txtits membership9.00 Btext/plain2023-17-07Admin</value>
      <webElementGuid>55050127-86dc-4a74-b876-f7292e4b887a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout orangehrm-upgrade-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;orangehrm-background-container&quot;]</value>
      <webElementGuid>4685f6a3-4cdd-47cc-802b-3a779fd0bfaa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div</value>
      <webElementGuid>6fa4803c-cdad-431a-9086-9bd459dfc060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>7b529a70-e52b-4790-b487-7b427fb05eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'manda userPersonal DetailsContact DetailsEmergency ContactsDependentsImmigrationJobSalaryReport-toQualificationsMembershipsAssigned Memberships Add No Records FoundMembershipSubscription Paid BySubscription AmountCurrencySubscription Commence DateSubscription Renewal DateActionsAttachments Add (1) Record FoundFile NameDescriptionSizeTypeDate AddedAdded ByActionsabc.txtits membership9.00 Btext/plain2023-17-07Admin' or . = 'manda userPersonal DetailsContact DetailsEmergency ContactsDependentsImmigrationJobSalaryReport-toQualificationsMembershipsAssigned Memberships Add No Records FoundMembershipSubscription Paid BySubscription AmountCurrencySubscription Commence DateSubscription Renewal DateActionsAttachments Add (1) Record FoundFile NameDescriptionSizeTypeDate AddedAdded ByActionsabc.txtits membership9.00 Btext/plain2023-17-07Admin')]</value>
      <webElementGuid>937c5634-3cc1-421c-8df1-775e6a155323</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
