<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Contact DetailsAddressStreet 1Street 2CityStateProvinceZipPostal CodeCountry-- Select --TelephoneHomeMobileWorkEmailWork EmailOther Email  Required Save</name>
   <tag></tag>
   <elementGuidId>a59f7d7b-9397-4e25-9086-7f8b13e7e1f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.orangehrm-horizontal-padding.orangehrm-vertical-padding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8ae72d95-37d9-4598-887a-e2468bf58d53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>orangehrm-horizontal-padding orangehrm-vertical-padding</value>
      <webElementGuid>a7214db3-27fc-4b92-bcc3-41d8fa32ce0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contact DetailsAddressStreet 1Street 2CityState/ProvinceZip/Postal CodeCountry-- Select --TelephoneHomeMobileWorkEmailWork EmailOther Email * Required Save </value>
      <webElementGuid>fcc3d989-8aac-49ca-b4a6-4e447c710276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout orangehrm-upgrade-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;orangehrm-background-container&quot;]/div[@class=&quot;orangehrm-card-container&quot;]/div[@class=&quot;orangehrm-edit-employee&quot;]/div[@class=&quot;orangehrm-edit-employee-content&quot;]/div[@class=&quot;orangehrm-horizontal-padding orangehrm-vertical-padding&quot;]</value>
      <webElementGuid>51f52220-53e7-4c4f-a2ba-1aa7f6309932</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div/div/div[2]/div</value>
      <webElementGuid>e62e870c-00bd-4eed-9958-f50477465e88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Memberships'])[1]/following::div[2]</value>
      <webElementGuid>75995489-34dd-4342-a79c-b8282a2bf90f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qualifications'])[1]/following::div[3]</value>
      <webElementGuid>a3986211-778f-447a-9420-5700b32f8256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div</value>
      <webElementGuid>dee50bb2-34c7-4594-8ae2-e69fc162392c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Contact DetailsAddressStreet 1Street 2CityState/ProvinceZip/Postal CodeCountry-- Select --TelephoneHomeMobileWorkEmailWork EmailOther Email * Required Save ' or . = 'Contact DetailsAddressStreet 1Street 2CityState/ProvinceZip/Postal CodeCountry-- Select --TelephoneHomeMobileWorkEmailWork EmailOther Email * Required Save ')]</value>
      <webElementGuid>911ebafc-c079-422c-880c-3b7765359a98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
